apiVersion: apps/v1
kind: Deployment
metadata: # Nama dan label dari deployment
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1 # Untuk sekarang hanya menggunakan 1 replica
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
      - name: {{ .Release.Name }}-data # Menggunakan persistent volume minecraft-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data-pvc # Menggunakan persistent volume claim minecraft-data-claim
      containers:
      - name: {{ .Release.Name }} 
        image: itzg/bungeecord:latest # Mengambil image Bungeecord dari repository docker
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
        env:
          - name:  TYPE
            value: '{{ .Values.bungeecord.type }}'
          - name: WATERFALL_VERSION
            value: '{{ .Values.bungeecord.version }}'
          - name: WATERFALL_BUILD_ID
            value: '{{ .Values.bungeecord.build_id }}'
          - name: ENABLE_RCON
            value: '{{ .Values.bungeecord.rcon }}'
          - name: INIT_MEMORY
            value: '{{ .Values.bungeecord.init_memory }}'
          - name: MAX_MEMORY
            value: '{{ .Values.bungeecord.max_memory }}'
          - name: SPIGET_PLUGINS
            value: '{{ .Values.bungeecord.plugins }}'
        ports:
        - containerPort: 25577
          name: bungeecord
        - containerPort: 9225
          name: metrics
          protocol: TCP
        - containerPort: 35353
          name: multipaper
        volumeMounts: # Path dari directory yang akan digunakan dan di mount ke PV
          - name: {{ .Release.Name }}-data
            mountPath:  '/server'
