apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: kube-prometheus-stack
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: {{ .Release.Name }}
    rules:
    - record: {{ .Release.Name }}_online_players
      expr: sum(bungeecord_online_players{namespace="{{ .Release.Namespace }}"})
      labels:
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}
    - record: {{ .Release.Name }}_online_server
      expr: kube_statefulset_replicas{namespace="{{ .Release.Namespace }}"}
      labels:
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}