apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 25577
      nodePort: {{ .Values.bungeecord.bungee_port }}
      name: bungeecord
    - port: 35353
      nodePort: {{ .Values.bungeecord.master_port }}
      name: multipaper
  selector:
    app: {{ .Release.Name }}
