apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      relabelings:
      - sourceLabels: 
        - __meta_kubernetes_pod_node_name
        targetLabel: server_name
      targetPort: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}