apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler # HPA
metadata:
  name: {{ .Release.Name }}-hpa # Nama dari HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet 
    name: {{ .Release.Name }} # Nama statefulset yang akan di-autoscaling
  minReplicas: 3 # Minimal replika yang dapat dijalankan
  maxReplicas: 10 # Maksimal replika yang dapat dijalankan
  metrics:
  - type: Object
    object:
      metric:
        name: {{ .Values.autoscaler.metrics_name }}
      describedObject:
        apiVersion: {{ .Values.autoscaler.metrics_api }}
        kind: {{ .Values.autoscaler.metrics_kind }}
        name: {{ .Values.autoscaler.metrics_label }}
      target:
        type: {{ .Values.autoscaler.target_type }}
        value: {{ .Values.autoscaler.target_value }}
  