apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-0
spec:
  type: NodePort
  ports:
    - name: nodeport
      port: 9940
      nodePort: 30940
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-0
